os: linux
dist: focal

language: java
jdk: openjdk11

cache:
  directories:
  - $HOME/.m2

  
before_deploy:
  - cp .travis.settings.xml $HOME/.m2/settings.xml
  - git checkout master
  - cd docs/asciidoc/deploy
deploy:
  skip_cleanup: true
  provider: script
  script: mvn -B deploy -DskipChecks
  
  branches:
  only:
    - master
