os: linux
dist: focal

language: java
jdk: openjdk11

cache:
  directories:
  - $HOME/.m2

script:
  - mvn --version

before_deploy:
  - cp .travis.settings.xml $HOME/.m2/settings.xml
  - cd docs/asciidoc/deploy
  - git checkout master

deploy:
  skip_cleanup: true
  provider: script
  script: mvn install
